# Setup
title:               'James Howard'
tagline:             'A Mathematician, a Different Kind of Mathematician, and a Statistician'
description:         'A Mathematician, a Different Kind of Mathematician, and a Statistician'
url:                 'https://jameshoward.us'
baseurl:             ''
twitter_username:    'k3jph'

# About/contact
author:
  name:              'James P. Howard, II'
  url:               'https://jameshoward.us'
  email:             'jh@jameshoward.us'

# Gems
plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll/footnotes
  - jekyll-algolia

exclude: ["Rakefile", "Main Website.code-workspace", ".jekyll-cache", ".gitignore", "_deploy"]

# Pagination
autopages:
  enabled: false
  tags: 
    layouts: 
      - tag.html
     # - autopage_collections_tags.html
     # - autopage_tags.html
    enabled: true

# This site uses the pretty permalink structure, this renders all urls with a slash / at the end and 
# no file endings, I guess that is considered pretty :)
permalink: pretty

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

# Custom vars
version:             1.1.0
google_analytics_id: UA-79581-8

# Scholar settings
scholar:
  style: mla

# Iframely!
iframely-key:       176ff6184ababb980170f6037497fb6a

algolia:
  application_id:       GI59X4R5CO
  index_name:           jekyll-jameshoward-us
  search_only_api_key:  867898ddd747a87edb66f2a825909281
