# Setup
title:               'James Howard'
tagline:             'A Mathematician, a Different Kind of Mathematician, and a Statistician'
description:         'A Mathematician, a Different Kind of Mathematician, and a Statistician'
url:                 'https://jameshoward.us'
baseurl:             ''
twitter_username:    'k3jph'

# About/contact
author:
  name:              'James P. Howard, II'
  url:               'https://jameshoward.us'
  email:             'jh@jameshoward.us'

twitter:
  username: k3jph
  card: summary

facebook:
  app_id: 364480777048278

logo: /assets/images/jhoward-greenglow.jpg

social:
  name: Ben Balter
  links:
    - https://twitter.com/k3jph
    - https://www.facebook.com/k3jph
    - https://www.linkedin.com/in/k3jph
    - https://github.com/k3jph
    - https://keybase.io/howardjp

# Gems
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-algolia

exclude: 
  - .gitignore
  - .jekyll-cache
  - _bibliography
  - deploy
  - Gemfile
  - Gemfile.lock
  - "Main Website.code-workspace"
  - Rakefile

# This site uses the pretty permalink structure, this renders all urls with a slash / at the end and 
# no file endings, I guess that is considered pretty :)
permalink: pretty

# Custom vars
version:             1.1.0
google_analytics_id: UA-79581-8

# Scholar settings
scholar:
  style: mla

# Iframely!
iframely-key:       176ff6184ababb980170f6037497fb6a

algolia:
  application_id:       GI59X4R5CO
  index_name:           jekyll-jameshoward-us
  search_only_api_key:  867898ddd747a87edb66f2a825909281
  # Exclude more files from indexing
  files_to_exclude:
    - tag.md